### ISSUE TITLE
Failed to Build ant test

### ISSUE THREAD

**Issue by lonespartan12** [jody/helloCS3250#54]
**Bug Description:** When trying to run the ant test test from the main project it will fail to build. specifically stating that the "/home/dev/cs3250/helloCS3250/build.xml:119 /home/dev/cs3250/helloCS3250/reports/testresults does not exist." So the xml file is not creating the directory to store the test results report.

**To Reproduce:** To repeat this error follow the instruction in the project readme. More specifically type in "ant test" in the terminal after copying and compiling the project.

**Expected behavior:** A test report should be generated as an html file and placed in the reports directory.

**System info:**
**OS:** Ubuntu V21.01
**Browser:** Mozilla
**Version:** helloCS3250 current main version.

**Additional Context:** This appears to be an issue with the XML no creating the reports directory when the project is run. The XML file should be creating the the reports directory with the other directories when the project is cleaned and rebuilt.

**Comment by jody** [comment]
Cannot reproduce on Darwin/BSD/OSX system.
Here is a transcript from the clone of the repository through running the build/test and observing no error.

```
[jozu:/tmp] jody% git clone https://github.com/jody/helloCS3250.git
Cloning into 'helloCS3250'...
remote: Enumerating objects: 91, done.
remote: Counting objects: 100% (91/91), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 91 (delta 29), reused 61 (delta 13), pack-reused 0
Receiving objects: 100% (91/91), 6.40 MiB | 15.20 MiB/s, done.
Resolving deltas: 100% (29/29), done.
[jozu:/tmp] jody% cd helloCS3250
[jozu:/tmp/helloCS3250] jody% ls
LICENSE     README.md   build.xml   lib/        myManifest  src/
[jozu:/tmp/helloCS3250] jody% ant test
Buildfile: /private/tmp/helloCS3250/build.xml

compile:
    [mkdir] Created dir: /private/tmp/helloCS3250/build/classes
    [javac] Compiling 4 source files to /private/tmp/helloCS3250/build/classes

test.console.launcher:
     [java] 
     [java] Thanks for using JUnit! Support its development at https://junit.org/sponsoring
     [java] 
     [java] .
     [java] +-- JUnit Jupiter [OK]
     [java] | '-- HelloWorldTest [OK]
     [java] |   +-- sayHelloBasicsTest() [OK]
     [java] |   +-- unnecessaryTest() [OK]
     [java] |   +-- sayHelloNullTest() [OK]
     [java] |   +-- sayHelloEmptyStringTest() [OK]
     [java] |   '-- groupedAssertionTest() [OK]
     [java] '-- JUnit Vintage [OK]
     [java] 
     [java] Test run finished after 553 ms
     [java] [         3 containers found      ]
     [java] [         0 containers skipped    ]
     [java] [         3 containers started    ]
     [java] [         0 containers aborted    ]
     [java] [         3 containers successful ]
     [java] [         0 containers failed     ]
     [java] [         5 tests found           ]
     [java] [         0 tests skipped         ]
     [java] [         5 tests started         ]
     [java] [         0 tests aborted         ]
     [java] [         5 tests successful      ]
     [java] [         0 tests failed          ]
     [java] 
[junitreport] Processing /private/tmp/helloCS3250/reports/testresults/TESTS-TestSuites.xml to /var/folders/qd/z_j9v_tx2cg7s69y2982ysvc0000gn/T/null745548559
[junitreport] Loading stylesheet jar:file:/opt/local/share/java/apache-ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 623ms
[junitreport] Deleting: /var/folders/qd/z_j9v_tx2cg7s69y2982ysvc0000gn/T/null745548559

unitTest:

test:

BUILD SUCCESSFUL
Total time: 3 seconds
[jozu:/tmp/helloCS3250] jody% ls reports/
testresults/
[jozu:/tmp/helloCS3250] jody% ls reports/testresults/
0_JUnit Jupiter-out.html  TEST-junit-vintage.xml    alltests-fails.html       package-frame.html
0_JUnit Jupiter.html      TESTS-TestSuites.xml      alltests-skipped.html     package-summary.html
1_JUnit Vintage-out.html  all-tests.html            index.html                stylesheet.css
1_JUnit Vintage.html      allclasses-frame.html     overview-frame.html
TEST-junit-jupiter.xml    alltests-errors.html      overview-summary.html
[jozu:/tmp/helloCS3250] jody% 
```

**Comment by lonespartan12** [comment]
Cannot reproduce successful results on Ubuntu 21.04
Here is a transcript from the clone of the repository through running the build/test and observing error

```
dev@osboxes:/tmp$ pwd
/tmp
dev@osboxes:/tmp$ git clone https://github.com/jody/helloCS3250.git
Cloning into 'helloCS3250'...
remote: Enumerating objects: 91, done.
remote: Counting objects: 100% (91/91), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 91 (delta 29), reused 61 (delta 13), pack-reused 0
Receiving objects: 100% (91/91), 6.40 MiB | 3.11 MiB/s, done.
Resolving deltas: 100% (29/29), done.
dev@osboxes:/tmp$ cd helloCS3250
dev@osboxes:/tmp/helloCS3250$ ls
build.xml  lib	LICENSE  myManifest  README.md	src
dev@osboxes:/tmp/helloCS3250$ ant test
Buildfile: /tmp/helloCS3250/build.xml

compile:
    [mkdir] Created dir: /tmp/helloCS3250/build/classes
    [javac] Compiling 4 source files to /tmp/helloCS3250/build/classes

test.console.launcher:
     [java] 
     [java] Thanks for using JUnit! Support its development at https://junit.org/sponsoring
     [java] 
     [java] Usage: ConsoleLauncher [-h] [--disable-ansi-colors] [--disable-banner]
     [java]                        [--fail-if-no-tests] [--scan-modules] [--scan-classpath[=PATH[;|:
     [java]                        PATH...]]]... [--details=MODE] [--details-theme=THEME]
     [java]                        [--reports-dir=DIR] [-c=CLASS]... [--config=KEY=VALUE]... [-cp=PATH
     [java]                        [;|:PATH...]]... [-d=DIR]... [-e=ID]... [-E=ID]...
     [java]                        [--exclude-package=PKG]... [-f=FILE]... [--include-package=PKG]...
     [java]                        [-m=NAME]... [-n=PATTERN]... [-N=PATTERN]... [-o=NAME]...
     [java]                        [-p=PKG]... [-r=RESOURCE]... [-t=TAG]... [-T=TAG]... [-u=URI]...
     [java] Launches the JUnit Platform from the console.
     [java]   -h, --help                 Display help information.
     [java]       --disable-ansi-colors  Disable ANSI colors in output (not supported by all
     [java]                                terminals).
     [java]       --disable-banner       Disable print out of the welcome message.
     [java]       --details=MODE         Select an output details mode for when tests are executed.
     [java]                                Use one of: none, summary, flat, tree, verbose. If 'none'
     [java]                                is selected, then only the summary and test failures are
     [java]                                shown. Default: tree.
     [java]       --details-theme=THEME  Select an output details tree theme for when tests are
     [java]                                executed. Use one of: ascii, unicode. Default: unicode.
     [java]       -cp, --classpath, --class-path=PATH[;|:PATH...]
     [java]                              Provide additional classpath entries -- for example, for
     [java]                                adding engines and their dependencies. This option can be
     [java]                                repeated.
     [java]       --fail-if-no-tests     Fail and return exit status code 2 if no tests are found.
     [java]       --reports-dir=DIR      Enable report output into a specified local directory (will
     [java]                                be created if it does not exist).
     [java]       --scan-modules         EXPERIMENTAL: Scan all resolved modules for test discovery.
     [java]   -o, --select-module=NAME   EXPERIMENTAL: Select single module for test discovery. This
     [java]                                option can be repeated.
     [java]       --scan-classpath, --scan-class-path[=PATH[;|:PATH...]]
     [java]                              Scan all directories on the classpath or explicit classpath
     [java]                                roots. Without arguments, only directories on the system
     [java]                                classpath as well as additional classpath entries supplied
     [java]                                via -cp (directories and JAR files) are scanned. Explicit
     [java]                                classpath roots that are not on the classpath will be
     [java]                                silently ignored. This option can be repeated.
     [java]   -u, --select-uri=URI       Select a URI for test discovery. This option can be repeated.
     [java]   -f, --select-file=FILE     Select a file for test discovery. This option can be
     [java]                                repeated.
     [java]   -d, --select-directory=DIR Select a directory for test discovery. This option can be
     [java]                                repeated.
     [java]   -p, --select-package=PKG   Select a package for test discovery. This option can be
     [java]                                repeated.
     [java]   -c, --select-class=CLASS   Select a class for test discovery. This option can be
     [java]                                repeated.
     [java]   -m, --select-method=NAME   Select a method for test discovery. This option can be
     [java]                                repeated.
     [java]   -r, --select-resource=RESOURCE
     [java]                              Select a classpath resource for test discovery. This option
     [java]                                can be repeated.
     [java]   -n, --include-classname=PATTERN
     [java]                              Provide a regular expression to include only classes whose
     [java]                                fully qualified names match. To avoid loading classes
     [java]                                unnecessarily, the default pattern only includes class
     [java]                                names that begin with "Test" or end with "Test" or
     [java]                                "Tests". When this option is repeated, all patterns will
     [java]                                be combined using OR semantics. Default: [^(Test.*|.+[.$]
     [java]                                Test.*|.*Tests?)$]
     [java]   -N, --exclude-classname=PATTERN
     [java]                              Provide a regular expression to exclude those classes whose
     [java]                                fully qualified names match. When this option is repeated,
     [java]                                all patterns will be combined using OR semantics.
     [java]       --include-package=PKG  Provide a package to be included in the test run. This
     [java]                                option can be repeated.
     [java]       --exclude-package=PKG  Provide a package to be excluded from the test run. This
     [java]                                option can be repeated.
     [java]   -t, --include-tag=TAG      Provide a tag or tag expression to include only tests whose
     [java]                                tags match. When this option is repeated, all patterns
     [java]                                will be combined using OR semantics.
     [java]   -T, --exclude-tag=TAG      Provide a tag or tag expression to exclude those tests whose
     [java]                                tags match. When this option is repeated, all patterns
     [java]                                will be combined using OR semantics.
     [java]   -e, --include-engine=ID    Provide the ID of an engine to be included in the test run.
     [java]                                This option can be repeated.
     [java]   -E, --exclude-engine=ID    Provide the ID of an engine to be excluded from the test
     [java]                                run. This option can be repeated.
     [java]       --config=KEY=VALUE     Set a configuration parameter for test discovery and
     [java]                                execution. This option can be repeated.
     [java] org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-vintage' failed to discover tests
     [java] 	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:111)
     [java] 	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:85)
     [java] 	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:92)
     [java] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
     [java] 	at org.junit.platform.console.tasks.ConsoleTestExecutor.executeTests(ConsoleTestExecutor.java:66)
     [java] 	at org.junit.platform.console.tasks.ConsoleTestExecutor.lambda$execute$0(ConsoleTestExecutor.java:58)
     [java] 	at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:33)
     [java] 	at org.junit.platform.console.tasks.ConsoleTestExecutor.execute(ConsoleTestExecutor.java:58)
     [java] 	at org.junit.platform.console.ConsoleLauncher.executeTests(ConsoleLauncher.java:95)
     [java] 	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:73)
     [java] 	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:50)
     [java] 	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:43)
     [java] 	at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:37)
     [java] Caused by: org.junit.platform.commons.JUnitException: Unsupported version of junit:junit: 3.8.2. Please upgrade to version 4.12 or later.
     [java] 	at org.junit.vintage.engine.JUnit4VersionCheck.checkSupported(JUnit4VersionCheck.java:49)
     [java] 	at org.junit.vintage.engine.JUnit4VersionCheck.checkSupported(JUnit4VersionCheck.java:35)
     [java] 	at org.junit.vintage.engine.VintageTestEngine.discover(VintageTestEngine.java:62)
     [java] 	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:103)
     [java] 	... 12 more
     [java] 
     [java] Java Result: 255

BUILD FAILED
/tmp/helloCS3250/build.xml:119: /tmp/helloCS3250/reports/testresults does not exist.

Total time: 1 second
dev@osboxes:/tmp/helloCS3250$ ls reports/
ls: cannot access 'reports/': No such file or directory

```

**Comment by jody** [comment]
No response.
